# -*- coding: utf-8 -*-
"""PLBA_Project_file_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYHmA3ngwuJGATbqEy7coFL0kXPB8lPq
"""

import pandas as pd
import numpy as np

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/NYA/superstore_final_dataset_new.csv"

# Read the CSV file using 'latin-1' encoding
ss = pd.read_csv(path, encoding='latin-1')
ss.head()

ss.isnull().sum()

ss.info()

"""**Cleaning and Transformation of the Data:**

**Checking for Duplicates**
"""

# Check for duplicates
duplicates = ss[ss.duplicated()]

# Count the number of duplicates
num_duplicates = duplicates.shape[0]

# Display the results
if num_duplicates > 0:
    print(f"Number of duplicate rows: {num_duplicates}")
    print("\nDuplicate Rows:")
    print(duplicates)
else:
    print("No duplicates found.")

"""Converting Data Types"""

ss['Order_Date']=pd.to_datetime(ss['Order_Date'],format='%d/%m/%Y')
ss['Ship_Date']=pd.to_datetime(ss['Ship_Date'],format='%d/%m/%Y')
ss.info()

"""Creating New Columns"""

ss['Days_Difference'] = (ss['Ship_Date'] - ss['Order_Date']).dt.days
ss.info()

"""Postal codes should be in Int after imputation

**Exploratory Analysis**

Data Overview
"""

# Check the shape of the dataset
print(f"Shape of the dataset: {ss.shape}")

# Check data types and non-null counts
print(ss.info())

"""Descriptive Statistics"""

# Summary statistics for numerical columns
ss.describe()

# Count unique values in categorical columns
unique_counts = {col: ss[col].nunique() for col in ss.select_dtypes(include='object').columns}
print("Unique value counts for categorical columns:\n", unique_counts)

"""Missing Values Analysis"""

# Calculate the overall percentage of null values
total_nulls = ss.isnull().sum().sum()  # Total number of nulls in the DataFrame
total_values = ss.size  # Total number of values in the DataFrame
percentage_nulls = (total_nulls / total_values) * 100  # Calculate percentage

print(f'Overall percentage of null values: {percentage_nulls:.2f}%')

"""Distribution Analysis"""

#Sales Distribution

import matplotlib.pyplot as plt  # Import the matplotlib library
plt.figure(figsize=(10, 6))
plt.hist(ss['Sales'].dropna(), bins=50, alpha=0.7, color='blue')
plt.title('Sales Distribution')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.grid(axis='y')
plt.show()

#Days Difference Distribution

plt.figure(figsize=(10, 6))
plt.hist(ss['Days_Difference'].dropna(), bins=30, alpha=0.7, color='green')
plt.title('Days Difference Distribution')
plt.xlabel('Days Difference')
plt.ylabel('Frequency')
plt.grid(axis='y')
plt.show()

"""Categorical Analysis"""

#Ship Mode Analysis

plt.figure(figsize=(10, 6))
ss['Ship_Mode'].value_counts().plot(kind='bar', color='purple', alpha=0.7)
plt.title('Distribution of Ship Modes')
plt.xlabel('Ship Mode')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

#Customer Segment Analysis

plt.figure(figsize=(10, 6))
ss['Segment'].value_counts().plot(kind='bar', color='orange', alpha=0.7)
plt.title('Distribution of Customer Segments')
plt.xlabel('Segment')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

"""**Imputing missing values**

**Ship_Date and Day_Difference columns Imputation:**
"""

ss['Ship_Mode'].unique()

average_days = ss.groupby('Ship_Mode')['Days_Difference'].mean().reset_index()
average_days

average_days = ss.groupby('Ship_Mode')['Days_Difference'].mean().reset_index()
first_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'First Class', 'Days_Difference'].values[0])
second_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'Second Class', 'Days_Difference'].values[0])
standard_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'Standard Class', 'Days_Difference'].values[0])

print(first_class_avg_days)
print(second_class_avg_days)
print(standard_class_avg_days)

# Finding the average number of days based on Ship_Mode
ss['Days_Difference'] = (ss['Ship_Date'] - ss['Order_Date']).dt.days
ss['Days_Difference'].fillna(ss['Days_Difference'].mean(), inplace=True)
ss['Days_Difference'] = ss['Days_Difference'].astype(int) # Changed line: Convert each element to int
average_days = ss.groupby('Ship_Mode')['Days_Difference'].mean().reset_index()
first_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'First Class', 'Days_Difference'].values[0])
second_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'Second Class', 'Days_Difference'].values[0])
standard_class_avg_days = int(average_days.loc[average_days['Ship_Mode'] == 'Standard Class', 'Days_Difference'].values[0])

# Define a function to calculate Ship_Date based on Ship_Mode
def calculate_ship_date(row):
    if pd.notnull(row['Ship_Date']):
        return row['Ship_Date']  # Return existing Ship_Date if available

    # Calculate Ship_Date based on Ship_Mode
    if row['Ship_Mode'] == 'Same Day':
        return row['Order_Date']  # Same day shipping
    elif row['Ship_Mode'] == 'First Class':
        return row['Order_Date'] + pd.Timedelta(days=first_class_avg_days)  # 2 day for First Class
    elif row['Ship_Mode'] == 'Standard Class':
        return row['Order_Date'] + pd.Timedelta(days=standard_class_avg_days)  # 5 days for Standard Class
    elif row['Ship_Mode'] == 'Second Class':
        return row['Order_Date'] + pd.Timedelta(days=second_class_avg_days)  # 3 days for Second Class
    else:
        return np.nan  # If no matching mode, return NaN

# Apply the function to the DataFrame
ss['Ship_Date'] = ss.apply(calculate_ship_date, axis=1)

# Display the updated DataFrame
ss.head()

ss.info()

"""**Ship_Mode column imputation:**

"""

ss['Days_Difference'].describe()

# Define a mapping function for Ship_Mode based on Days_Difference
def impute_ship_mode(days):
    if pd.isna(days):
        return None
    elif days == 0:
        return 'Same Day'
    elif days <= 2:
        return 'First Class'
    elif 3 <= days <= 5:
        return 'Standard Class'
    elif days > 5:
        return 'Second Class'
    return None

# Apply the function to fill missing Ship_Mode values based on Days_Difference
ss['Ship_Mode'] = ss['Ship_Mode'].combine_first(ss['Days_Difference'].apply(impute_ship_mode))

# Display the updated DataFrame
ss[['Row_ID', 'Order_ID', 'Ship_Mode', 'Days_Difference']]

ss.isnull().sum()

"""**Customer_Name Column imputation:**

"""

ss['Customer_ID'].nunique()

# Group by Customer_ID and aggregate the most common Customer_Name
mode_customer_names = ss.groupby('Customer_ID')['Customer_Name'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)

# Update the Customer_Name in the original DataFrame
ss['Customer_Name'] = ss['Customer_Name'].combine_first(ss['Customer_ID'].map(mode_customer_names))

# Display the updated DataFrame
ss.head()

ss.isnull().sum()

ss['Customer_Name'].nunique()

"""**Segment column Imputation:**"""

ss['Segment'].unique()

# Group by Customer_Name and find the most common Segment
mode_segments = ss.groupby('Customer_Name')['Segment'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)

# Map the most common segments back to the original DataFrame
ss['Segment'] = ss['Segment'].combine_first(ss['Customer_Name'].map(mode_segments))

# Optionally fill remaining NaNs with a predefined value or mode
ss['Segment'].fillna('Unknown', inplace=True)

# Display the updated DataFrame
ss.head()

ss.info()

"""**Country Column Imputation:**"""

ss['Country'].unique()

#Filling the missing values in Country column with 'United States'.
ss['Country'].fillna('United States', inplace=True)

ss['Country'].unique()

ss.info()

"""**Imputation of City Column**"""

# finding postal codes for all the cities
ss_cities =ss[['City', 'Postal_Code']]
ss_cities.dropna(inplace = True)
ss_cities.drop_duplicates(inplace = True)
ss_cities.nunique()

# mapping cities and postal codes
grouped_cities = ss_cities.groupby(['City', 'Postal_Code']).size().reset_index(name='Frequency')

city_dict = {}
for _, row in grouped_cities.iterrows():
    city = row['City']
    postal_code = row['Postal_Code']
    frequency = row['Frequency']

    if city not in city_dict:
        city_dict[city] = {}

    city_dict[city][postal_code] = frequency

# finding city by postal codes
def find_city_by_postal_code(city_dict, postal_code):
    for city, postal_codes in city_dict.items():
        if postal_code in postal_codes:
            return city
    return None

# filling city values into the DataFrame
for i in range(len(ss)):
    if pd.isnull(ss['City'][i]):
        ss['City'][i] = find_city_by_postal_code(city_dict, ss['Postal_Code'][i])

ss['City'].isnull().sum()

ss['City'].fillna('Unknown', inplace=True)

ss.info()

"""**Imputation of State Column**"""

ss_states = ss[['State', 'Postal_Code']]
ss_states.dropna(inplace = True)
ss_states.drop_duplicates(inplace=True)
ss_states.isnull().sum()

ss[ss['State'].isnull() & ss['Postal_Code'].isnull()].shape

# mapping states and postal codes
grouped_states = ss_states.groupby(['State', 'Postal_Code']).size().reset_index(name='Frequency')


state_dict = {}
for _, row in grouped_states.iterrows():
    state = row['State']
    postal_code = row['Postal_Code']
    frequency = row['Frequency']

    if state not in state_dict:
        state_dict[state] = {}

    state_dict[state][postal_code] = frequency

# finding state by postal codes
def find_state_by_postal_code(state_dict, postal_code):
    for state, postal_codes in state_dict.items():
        if postal_code in postal_codes:
            return state
    return None

# filling state values into the DataFrame
for i in range(len(ss)):
    if type(ss['State'][i]) == float:
        ss['State'][i] = find_state_by_postal_code(state_dict, ss['Postal_Code'][i])

ss['State'].isnull().sum()

ss['State'].fillna('Unknown', inplace=True)

ss.info()

"""**Imputation of Postal_Code Column**"""

ss['Postal_Code'].isnull().sum()

# Impute missing 'Postal_Code' based on 'City', 'State', and 'Region'
ss['Postal_Code'] = ss.groupby(['City', 'State', 'Region'])['Postal_Code'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

# Verify imputation by checking for missing values
print(ss['Postal_Code'].isnull().sum())  # Expected output: 0, if imputation was successful

(ss['Postal_Code']=='Unknown').sum()

# Drop rows where 'Postal_Code' is 'Unknown' or any placeholder value
ss = ss[ss['Postal_Code'] != 'Unknown']

# Verify the result by checking the shape of the DataFrame after dropping
print(ss.shape)  # Displays the new shape of the DataFrame after dropping rows

ss.info()

"""**Imputation of Product_Name Column**"""

ss['Product_Name'].nunique()

ss['Product_ID'].nunique()

# Assuming df is your DataFrame
# Fill missing 'Product_Name' based on 'Product_ID'
ss['Product_Name'] = ss.groupby('Product_ID')['Product_Name'].transform(lambda x: x.fillna(method='ffill').fillna(method='bfill'))

# Check the result
print(ss['Product_Name'].isnull().sum())  # Should be 0 if all missing values are imputed

ss.info()

"""**Imputation of Sub_Category Column**"""

ss['Sub_Category'].isnull().sum()

# Impute missing 'Sub_Category' values based on 'Product_ID' and 'Category'
ss['Sub_Category'] = ss.groupby(['Product_ID', 'Category'])['Sub_Category'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

ss['Sub_Category'].isnull().sum()

(ss['Sub_Category']=='Unknown').sum()

"""**Imputation of Sales Column**"""

ss['Sales'].isnull().sum()

# finding mean of sales based on region,category and subcategory
mean_sales = ss.groupby(['Region', 'Category', 'Sub_Category'])['Sales'].mean().reset_index()
ss = pd.merge(ss, mean_sales, on=['Region', 'Category', 'Sub_Category'], suffixes=('', '_mean'))
ss['Sales'] = ss['Sales'].fillna(ss['Sales_mean'])
ss.drop("Sales_mean",axis=1,inplace=True)

ss.info()

"""**Analysis of the Superstore:**

**5.1.	What are the trends in total sales over time (monthly, quarterly, annually)?**

Steps of Analysis


1.  Aggregate total sales over time for monthly, quarterly, and annual periods.
2.  Visualize the trends using matplotlib.
3.  Calculate Growth Rates: Calculate the percentage change in sales from month to month, quarter to quarter, and year to year.
"""

import matplotlib.pyplot as plt

# Set the 'Order_Date' as the index
ss.set_index('Order_Date', inplace=True)

# Monthly Total Sales
monthly_sales = ss.resample('M')['Sales'].sum()

# Quarterly Total Sales
quarterly_sales = ss.resample('Q')['Sales'].sum()

# Annual Total Sales
annual_sales = ss.resample('A')['Sales'].sum()

# Plotting the trends
plt.figure(figsize=(18, 6))

# Monthly Sales
plt.subplot(1, 3, 1)
plt.plot(monthly_sales.index, monthly_sales, marker='o')
plt.title('Monthly Total Sales')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)

# Quarterly Sales
plt.subplot(1, 3, 2)
plt.plot(quarterly_sales.index, quarterly_sales, marker='o', color='orange')
plt.title('Quarterly Total Sales')
plt.xlabel('Quarter')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)

# Annual Sales
plt.subplot(1, 3, 3)
plt.plot(annual_sales.index, annual_sales, marker='o', color='green')
plt.title('Annual Total Sales')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Monthly Growth Rate
monthly_growth = monthly_sales.pct_change() * 100

# Quarterly Growth Rate
quarterly_growth = quarterly_sales.pct_change() * 100

# Annual Growth Rate
annual_growth = annual_sales.pct_change() * 100

print("Monthly Growth Rate:")
print(monthly_growth)

print("\nQuarterly Growth Rate:")
print(quarterly_growth)

print("\nAnnual Growth Rate:")
print(annual_growth)

"""**5.2.	Which product categories generate the highest revenue, and how do they compare to one another?**"""

# Group by Category and sum the sales
category_revenue = ss.groupby('Category')['Sales'].sum().sort_values(ascending=False)

# Display the revenue by category
print(category_revenue)

# Plotting the revenue by category
plt.figure(figsize=(12, 6))
category_revenue.plot(kind='bar', color='skyblue')
plt.title('Total Revenue by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Total Sales Revenue')
plt.xticks(rotation=45)
plt.show()

total_revenue = ss['Sales'].sum()
category_percentage = (category_revenue / total_revenue) * 100
print(category_percentage)

"""**5.3.How do sales vary across different regions and cities, and what factors may influence these differences?**

Steps for Analysis


1.  Aggregate Sales by Region and City: Sum the total sales for each region and city.
2.  Visualize Sales Distribution: Use bar charts to visualize sales across regions and cities.
3.  Basic Comparison: Calculate and compare averages and total sales across regions and cities.
4. Understanding the Influencing Factors.
"""

# Total sales by region
sales_by_region = ss.groupby('Region')['Sales'].sum().sort_values(ascending=False)

# Total sales by city
sales_by_city = ss.groupby('City')['Sales'].sum().sort_values(ascending=False)

# Display results
print("Sales by Region:")
print(sales_by_region)
print("\nSales by City (Top 10):")
print(sales_by_city.head(10))  # Show top 10 cities

# Plotting sales by region
plt.figure(figsize=(12, 6))
sales_by_region.plot(kind='bar', color='skyblue')
plt.title('Total Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales Revenue')
plt.xticks(rotation=45)
plt.show()

# Plotting sales by city (top 10)
plt.figure(figsize=(12, 6))
sales_by_city.head(10).plot(kind='bar', color='lightgreen')
plt.title('Total Sales by City (Top 10)')
plt.xlabel('City')
plt.ylabel('Total Sales Revenue')
plt.xticks(rotation=45)
plt.show()

# Average sales by region
average_sales_by_region = ss.groupby('Region')['Sales'].mean()
print("\nAverage Sales by Region:")
print(average_sales_by_region)

# Average sales by city
average_sales_by_city = ss.groupby('City')['Sales'].mean()
print("\nAverage Sales by City (Top 10):")
print(average_sales_by_city.sort_values(ascending=False).head(10))  # Show top 10 cities

# Correlation with Days taken to ship from the order received
avg_days_by_region = ss.groupby('Region')['Days_Difference'].mean()
print("\nAverage Days Difference by Region:")
print(avg_days_by_region)

# Combining average sales and days difference for comparison
comparison_df = pd.DataFrame({
    'Average Sales': average_sales_by_region,
    'Average Days Difference': avg_days_by_region
})

print("\nComparison of Average Sales and Days Difference by Region:")
print(comparison_df)

gb=ss.groupby('Region')['Days_Difference']
gb.describe()

# Select only numeric columns for correlation calculation
numerical_cols = ss.select_dtypes(include=np.number).columns
correlation = ss[numerical_cols].corr()['Sales'].sort_values(ascending=False)
print("Correlation with Sales:")
print(correlation)

# You can also group by region or city to check the average Days_Difference
avg_days_by_region = ss.groupby('Region')['Days_Difference'].mean()
print("\nAverage Days Difference by Region:")
print(avg_days_by_region)

"""**Notes:**
Days_Difference (-0.007272):

The correlation between Sales and Days_Difference is also close to zero (-0.0072). This indicates that there is almost no linear relationship between the number of days difference and sales. This means that variations in shipping time do not seem to significantly affect sales in this dataset.

Average Days Difference by Region
The average days difference by region provides insights into shipping times across different areas:

Central (4.24 days)
East (4.09 days)
South (4.13 days)
West (4.11 days)
Interpretation of Average Days Difference
The average days difference in shipping times is relatively consistent across regions, with the Central region taking slightly longer on average.
Since the average shipping times do not differ significantly, it may indicate that shipping logistics are relatively uniform across regions.
Overall Insights
Sales and Days Difference: The very low correlation indicates that shipping time does not significantly impact sales in your dataset. This could suggest that customers are not deterred by shipping times or that other factors are more influential.

**5.4.	What is the relationship between customer segments and their purchasing behavior (average order value, frequency of purchases)?**

Steps for Analysis
1. Data Preparation: Ensuring the dataset has the necessary columns, particularly Customer_ID, Segment, Sales, and the frequency of purchases (which can be derived from the order count per customer).

2. Calculate Average Order Value (AOV):AOV can be calculated as total sales divided by the number of orders for each segment.

3. Calculate Purchase Frequency: Count the number of purchases for each customer and then aggregate this by segment to find the average frequency.

4. Visualization: Use bar charts or box plots to visualize the average order value and purchase frequency by customer segment.
"""

# Calculate total sales and order count per customer
customer_data = ss.groupby('Customer_ID').agg({
    'Sales': 'sum',
    'Order_ID': 'count'
}).reset_index()

# Rename columns for clarity
customer_data.rename(columns={'Sales': 'Total_Sales', 'Order_ID': 'Purchase_Count'}, inplace=True)
# Sort customer_data by Order Count in descending order
customer_data_sorted = customer_data.sort_values(by='Purchase_Count', ascending=False).reset_index()

# Display the sorted customer_data
print(customer_data_sorted)

# Merge back with segments
customer_segments = ss[['Customer_ID', 'Segment']].drop_duplicates()
merged_data = pd.merge(customer_data, customer_segments, on='Customer_ID')
merged_data

# Calculate Average Order Value (AOV) and Purchase Frequency
segment_analysis = merged_data.groupby('Segment').agg({'Total_Sales': 'sum', 'Purchase_Count': 'mean'}).reset_index()
segment_analysis

segment_analysis['Average_Order_Value'] = segment_analysis['Total_Sales'] / segment_analysis['Purchase_Count']
# Display results
print(segment_analysis[['Segment', 'Average_Order_Value', 'Purchase_Count']])

# Display results
print(segment_analysis[['Segment', 'Average_Order_Value', 'Purchase_Count']])

#Average Order Value by Segment
plt.figure(figsize=(12, 6))
plt.bar(segment_analysis['Segment'], segment_analysis['Average_Order_Value'], color='skyblue')
plt.title('Average Order Value by Customer Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Average Order Value')
plt.xticks(rotation=45)
plt.show()

#Purchase Frequency by Segment
plt.figure(figsize=(12, 6))
plt.bar(segment_analysis['Segment'], segment_analysis['Purchase_Count'], color='lightgreen')
plt.title('Average Purchase Frequency by Customer Segment')
plt.xlabel('Customer Segment')
plt.ylabel('Average Purchase Frequency')
plt.xticks(rotation=45)
plt.show()

"""**Notes:**
Interpreting the Results
Average Order Value:

Higher AOV in a particular segment suggests that customers in that segment are willing to spend more per order. This could indicate a preference for premium products or effective marketing strategies.
Purchase Frequency:

A higher average purchase frequency indicates that customers in that segment are more loyal or more engaged. This might be due to targeted promotions or tailored marketing efforts.
Comparative Insights:

Comparing AOV and purchase frequency across segments helps identify which segments are most profitable and engaged.
Segments with high frequency but low AOV may benefit from strategies aimed at upselling or cross-selling.
Reccomendation: Customer Feedback: Gather qualitative data on customer preferences to understand motivations behind purchasing behaviors.

**Recommendations**:

Upselling & Cross-selling: Target segments like Home Office and Unknown, which show lower AOV, with strategies aimed at increasing average order values.
Loyalty Programs: For high-frequency segments like Consumer and Corporate, loyalty programs or repeat purchase incentives could further increase engagement and sales.
Customer Feedback: Gathering qualitative insights from customers could help understand the reasons behind the differences in AOV and purchase frequency, allowing for more personalized marketing approaches.

**5.5.	Are there specific times of the year when sales peak, and how can this information be used for inventory management?**

Steps for Analysis

1. Extract Time Features: Create new columns for the month and year from the Order_Date to facilitate time-based analysis.

2. Aggregate Sales Data: Group the data by month and year to find total sales for each month.

3. Identify Peaks: Determine which months have the highest sales.

4. Make Recommendations for Inventory Management: Based on the analysis, provide insights on how to manage inventory.

5. Visualize the Sales Trends: Use a plot to visualize the sales data over time.
"""

ss.info()

ss.reset_index(inplace=True)

# Extract time features
ss['Year'] = ss['Order_Date'].dt.year
ss['Month'] = ss['Order_Date'].dt.month

# Aggregate sales data by month and year
monthly_sales = ss.groupby(['Year', 'Month'])['Sales'].sum().reset_index()
monthly_sales

peak_sales = monthly_sales.loc[monthly_sales.groupby('Year')['Sales'].idxmax()]
peak_sales

# Determine which months require high inventory management
# Assuming months with peak sales > some threshold need higher inventory
threshold = peak_sales['Sales'].mean()  # Example threshold: average peak sales
high_inventory_months = peak_sales[peak_sales['Sales'] > threshold]

print("Months needing high inventory management based on peak sales:")
print(high_inventory_months[['Year', 'Month', 'Sales']])

# Create a line plot with all data points shown
plt.figure(figsize=(14, 7))
for year in monthly_sales['Year'].unique():
    yearly_data = monthly_sales[monthly_sales['Year'] == year]
    plt.plot(yearly_data['Month'], yearly_data['Sales'], marker='o', label=year, alpha=0.8)

    # Highlight the peak sales
    peak_sales = yearly_data.loc[yearly_data['Sales'].idxmax()]
    plt.plot(peak_sales['Month'], peak_sales['Sales'], marker='o', markersize=10, color='red')  # Peak point
    plt.annotate(f'Peak: {peak_sales["Sales"]}',
                 xy=(peak_sales['Month'], peak_sales['Sales']),
                 xytext=(peak_sales['Month'] + 0.2, peak_sales['Sales'] - 10000),
                 arrowprops=dict(facecolor='black', arrowstyle='->'))

plt.title('Peak Sales by Month for Each Year with Highlighted Peaks')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(ticks=range(1, 13), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                                          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend(title='Year')
plt.grid()
plt.tight_layout()
plt.show()

"""**Notes:**
Inventory Management Recommendations
Based on the findings:

Increase Stock Levels: For months identified as peak months (e.g., November and December), increase stock levels in advance to meet expected demand.

Supplier Coordination: Work with suppliers to ensure timely delivery of products leading up to peak months.

Promotions and Marketing: Consider promotional campaigns during these peak months to maximize sales potential.

Seasonal Product Lines: Evaluate the introduction of seasonal products that align with peak months to leverage consumer demand.
"""



"""**5.6 Which shipping modes are most popular among different customer segments?**

Steps of Analysis
    
    1. Group the dataset based on Segment and Ship_Mode columns and aggregate the sum of Sales.
    2. Normalize sales to calculate percentages within each segment.
"""

shipping_segment_sales = ss.groupby(['Segment', 'Ship_Mode'])['Sales'].sum()
shipping_segment_percentage = shipping_segment_sales.groupby(level=0).apply(lambda x: 100 * x / x.sum()).unstack()
shipping_segment_percentage.plot(kind='bar', figsize=(10, 6), width=0.8)

plt.title('Shipping Modes Sales Percentage by Customer Segment', fontsize=16)
plt.xlabel('Customer Segment', fontsize=14)
plt.ylabel('Sales Percentage (%)', fontsize=14)
plt.xticks(rotation=0, fontsize=12)
plt.yticks(fontsize=12)
plt.legend(title='Shipping Modes', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

shipping_segment_percentage

"""The above graph clearly states that all the customers irrespective of the segement they belong to prioritize "Statndard Class" as their shipping mode. The least priority is given to the shipping mode "Same Day"

This could be due to the reason that the extra charge they have to pay for the faster delivery unless the delivery of the product is very urgent as we have seen i about 5 percent of the orders
"""



"""**5.7 Are certain days of the week or times of day associated with higher sales volumes?**

Steps for Analysis

1. Ensure 'Order_Date' is in datetime format
2. Extract day of the week and hour from the 'Order_Date'
3. Group by Day of the Week and sum sales
"""

ss['Order_Date'] = pd.to_datetime(ss['Order_Date'])
ss['Day_of_Week'] = ss['Order_Date'].dt.day_name()
sales_by_day = ss.groupby('Day_of_Week')['Sales'].sum()

days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
sales_by_day = sales_by_day.reindex(days_order)

# Plot sales by day of the week
plt.figure(figsize=(10, 5))
sales_by_day.plot(kind='bar', color='skyblue', alpha=0.8)
plt.title('Total Sales by Day of the Week', fontsize=16)
plt.xlabel('Day of the Week', fontsize=14)
plt.ylabel('Total Sales', fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

sales_by_day

"""Customers preferred to order the product equally on all the days except Thursday and Friday.This says that customers have very less tendency to place an order on Thursdays and Fridays. This could have been due to the several factors such as  promotional or marketing activity, customer behavior patterns, and operational constraints. By investigating these potential causes further, such as looking at past promotions or logistics patterns, businesses can make adjustments to ensure more consistent sales throughout the week.

**5.8 What are the top-selling product category within each region, and how can these insights be used to optimize inventory in different locations?**

Steps for Analysis

1. Group by Region and Category and sum the sales. Pivot the data to create a matrix where rows are regions and columns are categories
"""

region_category_sales = ss.groupby(['Region', 'Category'])['Sales'].sum().reset_index()
pivot_data = region_category_sales.pivot(index='Region', columns='Category', values='Sales')

plt.figure(figsize=(12, 8))

pivot_data.plot(kind='bar', stacked=False, figsize=(12, 8))

plt.title('Top-Selling Product categories by Region', fontsize=16)
plt.xlabel('Region', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Category', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

pivot_data

"""It has been clear that consumers have been purchasing more of technology items compared to others across all the regions except West where the category furniture has a slight lead in total number of sales over technology.

This could be due to the technological advancements that have been happening over the years. The variety .of products, customer dependency and the frequent discount programs could've also contributed to this purchasing patterns.

But still the purchasing of all the other category products is also significant. Consumers in genral are open to purchaase all types of products form this superstore.

**5.9 Analysis of Customer order frequency**

Steps for Analysis

1. Filter the customers who have more than one purchase
2. Find the percentage of repeat customers
"""

customer_purchase_counts = ss['Customer_ID'].value_counts()
repeat_buyers = customer_purchase_counts[customer_purchase_counts > 1]
total_customers = len(customer_purchase_counts)

repeat_buyers_percentage = (len(repeat_buyers) / total_customers) * 100

repeat_buyers_sales = ss[ss['Customer_ID'].isin(repeat_buyers.index)]['Sales'].sum()
one_time_buyers_sales = ss[~ss['Customer_ID'].isin(repeat_buyers.index)]['Sales'].sum()

fig, ax = plt.subplots(figsize=(8, 6))

ax.bar(['Repeat Buyers', 'One-Time Buyers'], [repeat_buyers_sales, one_time_buyers_sales], color=['green', 'blue'])
ax.set_title('Sales Comparison: Repeat Buyers vs One-Time Buyers')
ax.set_ylabel('Total Sales')
ax.set_xlabel('Customer Type')

plt.figtext(0.6, 0.8, f'Repeat Buyers: {repeat_buyers_percentage:.2f}%', fontsize=12, ha='left')

plt.tight_layout()
plt.show()

print(f"Percentage of Repeat Buyers: {repeat_buyers_percentage:.2f}%")
print(f"Total Sales from Repeat Buyers: ${repeat_buyers_sales:,.2f}")
print(f"Total Sales from One-Time Buyers: ${one_time_buyers_sales:,.2f}")

customer_order_frequency = ss['Customer_ID'].value_counts()

# Plotting the histogram
plt.figure(figsize=(10, 6))
plt.hist(customer_order_frequency, bins=range(1, customer_order_frequency.max()+2), edgecolor='black', color='skyblue')
plt.title('Customer Order Frequency Distribution')
plt.xlabel('Number of Orders per Customer')
plt.ylabel('Number of Customers')
plt.xticks(range(1, customer_order_frequency.max()+1))
plt.tight_layout()
plt.show()

customer_order_frequency

"""Almost almost all the customers are repeated cutomers.

If almost all customers are repeat customers, it signifies strong customer loyalty and satisfaction, leading to several key benefits:

Customer Loyalty and Retention: High repeat purchase rates indicate trust and satisfaction, leading to brand loyalty and word-of-mouth marketing.

Cost Efficiency: Retaining existing customers is more cost-effective than acquiring new ones, reducing marketing costs and leveraging referrals.

Predictable Revenue: Repeat customers contribute to consistent sales, making it easier to manage inventory and forecast cash flow.

Increased Customer Lifetime Value (CLV): Repeat customers generally spend more over time, increasing their overall value to the business. Upselling and cross-selling opportunities are more viable.

Customer Feedback: Loyal customers provide valuable insights for product or service improvement, helping businesses innovate and grow.

**5.10 Analysis of segment and category of the product**

Steps for Analysis

1. Group by Segment and Category and sum the sales
2. Pivot the data for better visualization (rows are Segments, columns are Categories)
"""

segment_category_sales = ss.groupby(['Segment', 'Category'])['Sales'].sum().reset_index()
pivot = segment_category_sales.pivot(index='Segment', columns='Category', values='Sales')

pivot.plot(kind='bar', stacked=False, figsize=(12, 6), colormap='Set3')

plt.title('Sales Distribution by Customer Segment and Product Category')
plt.xlabel('Customer Segment')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Product Categories', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

pivot

"""Simialr to the sales division by area, customers in each segement prioritize buying tecnological products it suggests that technology items are in high demand, driven by several factors:

Corporate Segment: Focuses on business technology (e.g., laptops, software).
Home Office Segment: Prioritizes productivity tech (e.g., video conferencing tools).
Consumer Segment: Prefers personal tech (e.g., smartphones, gaming systems).
Technological Dependence: All segments rely on technology for work, communication, and entertainment.

Marketing Influence: Targeted campaigns promote tech products, making them more desirable across segments.

Product Accessibility: Discounts, financing options, and innovation make tech products more accessible to all customers.
"""



